name: depoly to tengxunyun

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 10
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SRC_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: "docs/.vuepress/dist"
          REMOTE_HOST: "1.15.139.90"
          REMOTE_USER: "root"
          TARGET: "/usr/local/nginx/html"